###############
### BINNING ###
###############
concoct: True
min_contig_length: 1000
concoct_threads: 20
# Do QA on produced bins using Checkm?
checkm: False
pipeline_config_file: results/pipeline_config_binning.txt
