# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

pipelines:
  branches:
    master:
      - step:
          name: Install
          image: continuumio/miniconda3:latest
          caches:
            - condacache
          script:
            - mkdir -p envs/nbis-meta && conda env create --force -f envs/environment.yaml -p envs/nbis-meta
            - conda activate envs/nbis-meta
      - step:
          name: Dry-run
          image: continuumio/miniconda3:latest
          caches:
            - condacache
          script:
            - conda activate envs/nbis-meta
            - snakemake --configfile examples/binning/config.yaml -n
            - snakemake --configfile examples/centrifuge/config.yaml -n
            - snakemake --configfile examples/refmap/config.yaml -n
            - snakemake -n

definitions:
  caches:
    condacache: envs/nbis-meta