# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: continuumio/miniconda3:latest

pipelines:
  default:
    - step:
        name: Test
        script:
          - echo "Testing!"
  tags:
    v*:
    - step:
        name: Build and dry-run
        image: continuumio/miniconda3:latest
        script: # Modify the commands below to build your repository.
          - mkdir -p envs/nbis-meta && conda env create -f envs/environment.yaml -p envs/nbis-meta
          - conda activate envs/nbis-meta
          - snakemake -np
