# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

pipelines:
  tags:
    v*:
    - step:
        name: Install and dry-run
        image: continuumio/miniconda3:latest
        caches:
          - condacache
        script: # Modify the commands below to build your repository.
          - mkdir -p envs/nbis-meta && conda env create -f envs/environment.yaml -p envs/nbis-meta
          - conda activate envs/nbis-meta
          - snakemake --configfile examples/binning/config.yaml -np
          - snakemake --configfile examples/centrifuge/config.yaml -np
          - snakemake --configfile examples/refmap/config.yaml -np

definitions:
  caches:
    condacache: envs/nbis-meta