name: nbis-meta

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # core packages for workflow
  - python=3.7.6
  - snakemake-minimal=5.19.2
  - pandas=1.0.1
  - biopython=1.76

  # packages required to create snakemake reports
  - pygments
  - jinja2
  - networkx
  - pygraphviz
  - imagemagick
