name: nbis-meta

channels:
  - etetoolkit
  - conda-forge
  - biocore
  - bioconda

dependencies:
  - python=3.5.5
  - snakemake-minimal
  - seqtk=1.3
  - pandas=0.23.4
  - fastqc=0.11.8
  - metabat2=2.12.1
  - bowtie2=2.3.4.3
  - samtools=1.9
  - multiqc=1.6
  - cutadapt=1.18
  - megahit=1.1.3
  - tango=0.5.6
  - tqdm=4.29.1 # Some bug in later version of tqdm causes ZeroDivisionError
  - trimmomatic=0.38
  - diamond=0.9.22
  - prodigal=2.6.2
  - seaborn=0.9.0
  - picard=2.18.21
  - biopython=1.72
  - subread=1.6.3
  - ete3=3.1.1
  - conda=4.5.11
  - bedtools=2.27.1
  - fastuniq=1.1
  - gffutils=0.9
  - kraken2=2.0.7_beta
  - prokka=1.13.4
  - blast=2.5.0
  - sra-tools=2.9.6
  - fastani=1.1
  - barrnap=0.9
