pipeline_config_file: results/pipeline_config_centrifuge.txt
assembly: False
sample_list: examples/kraken/sample_annotation.tab
results_path: results/examples/kraken_classify
report_path: results/examples/kraken_classify/report
trimmomatic: False
phix_filter: False
kraken: True
kraken_prebuilt: "minikraken2_v2_8GB"
kraken_reduce_memory: True
