pipeline_config_file: results/pipeline_config_centrifuge.txt
assembly: False
sample_list: examples/centrifuge/sample_annotation.tab
results_path: results/examples/centrifuge_classify
report_path: results/examples/centrifuge_classify/report
trimmomatic: False
phix_filter: False
centrifuge: True
centrifuge_map_filtered: False
centrifuge_prebuilt: 'p+h+v'
