###############
### BINNING ###
###############
results_path: "results/examples"
maxbin: True
concoct: True
min_contig_length: [1000,2000]
maxbin_threads: 10
concoct_threads: 20
pipeline_config_file: results/pipeline_config_binning.txt
