$schema: "http://json-schema.org/draft-04/schema#"
description: Configuration schema
properties:
  ## PATHS ##
  workdir:
    type: string
    default: .
    description: Work directory for workflow
  sample_list:
    type: string
    description: Sample information file
  taxdb:
    type: string
    description: Directory to store taxonomy information
    default: resources/taxonomy
  results_path:
    type: string
    description: Main results directory
    default: results
  intermediate_path:
    type: string
    description: Intermediate results path
    default: results/intermediate
  temp_path:
    type: string
    description: Temporary path
    default: temp
  scratch_path:
    type: string
    description: Local storage path
    default: $TMPDIR
  resource_path:
    type: string
    description: Path to store resource files (databases etc)
    default: resources
  report_path:
    type: string
    description: Path to store report files
    default: results/report
  pipeline_config_file:
    type: string
    description: File with run information
    default: results/pipeline_config.txt
  ## PREPROCESSING ##
  trimmomatic:
    type: boolean
    description: Indicates whether to run trimmomatic
    default: true
  trimmomatic_home:
    type: string
    description: Path to trimmomatic jar files
    default: ""
  trim_adapters:
    type: boolean
    description: Whether to do adapter trimming with trimmomatic
    default: true
  pe_adapter_params:
    type: string
    description: Trimmomatic parameters for trimming adapters on paired-end samples
    default: 2:30:15
  se_adapter_params:
    type: string
    description: Trimmomatic parameters for trimming adapters on single-end samples
    default: 2:30:15
  pe_pre_adapter_params:
    type: string
    description: Trimmomatic parameters for trimming prior to adapter removal on paired-end samples
    default: ""
  se_pre_adapter_params:
    type: string
    description: Trimmomatic parameters for trimming prior to adapter removal on single-end samples
    default: ""
  pe_post_adapter_params:
    type: string
    description: Trimmomatic parameters for trimming after adapter removal on paired-end samples
    default: "LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:31"
  se_post_adapter_params:
    type: string
    description: Trimmomatic parameters for trimming after adapter removal on single-end samples
    default: "LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:31"
  cutadapt:
    type: boolean
    description: Indicates whether to run cutadapt
    default: false
  adapter_sequence:
    type: string
    description: Adapter sequence to trim with cutadapt
    default: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
  rev_adapter_sequence:
    type: string
    description: Reverse adapter sequence to trim with cutadapt
  fastuniq:
    type: boolean
    description: Indicates whether to run fastuniq
    default: false
  phix_filter:
    type: boolean
    description: Indicates whether to filter samples against the phiX genome
    default: false
  sortmerna:
    type: boolean
    description: Indicates whether to identify rRNA sequences in the samples
    default: false
  sortmerna_keep:
    type: string
    description: What to keep from sortmerna filtering (non_rRNA/rRNA)
    default: "non_rRNA"
    enum: ["non_rRNA", "rRNA"]
  sortmerna_remove_filtered:
    type: boolean
    description: Whether to remove filtered reads not specified by sortmerna_keep
    default: false
  sortmerna_dbs:
    type: array
    description: What databases to download for rRNA identification
    uniqueItems: true
    items:
      type: string
      enum: ["rfam-5s-database-id98.fasta","rfam-5.8s-database-id98.fasta","silva-arc-16s-id95.fasta","silva-arc-23s-id98.fasta","silva-bac-16s-id90.fasta","silva-bac-23s-id98.fasta","silva-euk-18s-id95.fasta","silva-euk-28s-id98.fasta"]
    default: ["rfam-5s-database-id98.fasta","rfam-5.8s-database-id98.fasta","silva-arc-16s-id95.fasta","silva-arc-23s-id98.fasta","silva-bac-16s-id90.fasta","silva-bac-23s-id98.fasta","silva-euk-18s-id95.fasta","silva-euk-28s-id98.fasta"]
  sortmerna_paired_strategy:
    type: string
    description: Whether to put both paired reads into rRNA bin (paired_in) or both reads in other bin (paired_out)
    default: "paired_in"
    enum: ["paired_in", "paired_out"]
  sortmerna_params:
    type: string
    description: "Additional parameters for sortmerna"
    default: "--num_alignments 1 -v"
  ## Postprocessing ##
  markduplicates:
    type: boolean
    description: Indicates whether to run MarkDuplicates for removing duplicates post mapping
    default: true
  picard_jar:
    type: string
    description: Path to picard jar file
    default: ""
  picard_path:
    type: string
    description: Path to picard path
    default: ""
  ## Assembly ##
  assembly:
    type: boolean
    description: Indicates whether to run assembly
    default: true
  assembly_threads:
    type: integer
    description: How many threads to use for assembly
    default: 20
    minimum: 1
  megahit_keep_intermediate:
    type: boolean
    description: Whether to keep intermediate contigs from Megahit
    default: false
  megahit_additional_settings:
    type: string
    description: Additional settings for Megahit
    default: "--min-contig-len 300 --prune-level 3"
  ## Annotation ##
  eggnog:
    type: boolean
    description: Indicates whether to run eggnog-mapper
    default: false
  pfam:
    type: boolean
    description: Indicates whether to run pfam_scan
    default: false
  taxonomic_annotation:
    type: boolean
    description: Indicates whether to run taxonomic annotation
    default: false
  diamond_dbpath:
    type: string
    description: Where to store diamond formatted database for taxonomic annotation
    default: resources/diamond
  diamond_dbtype:
    type: string
    description: What protein database to use for taxonomic annotation
    default: uniref100
    enum: ["uniref100", "uniref90", "uniref50", "nr"]
  diamond_threads:
    type: integer
    description: How many threads to use for diamond
    default: 20
    minimum: 1
  infernal:
    type: boolean
    description: Indicates whether to run infernal for nc-rRNA identification
    default: false
  infernal_threads:
    type: integer
    description: How many threads to use for infernal
    default: 2
    minimum: 1
  infernal_dbpath:
    type: string
    description: Where to store infernal database
    default: resources/infernal
  ## Binning ##
  binning:
    type: boolean
    description: Indicates whether to run binning on contigs
    default: false
  min_contig_length:
    type: number
    description: Minimum contig length for binning
    default: 1000
  binning_threads:
    type: integer
    description: Number of threads to use for binning
    default: 10
    minimum: 1
  checkm:
    type: boolean
    description: Indicates whether to check bin quality using checkm
    default: false
  ## Mapping ##
  bowtie2_threads:
    type: integer
    description: How many threads to use for bowtie2
    default: 10
    minimum: 1
  ## Reference based read mapping ##
  reference_map:
    type: boolean
    description: Indicates whether to run reference based mapping
    default: false
  refmap_min_read_count:
    type: integer
    description: Minimum read count for first-step filtering using centrifuge
    default: 50
  ## Classification ##
  classifier_db_path:
    type: string
    description: Parent directory for classifier databases
    default: resources/classify_db
  kraken:
    type: boolean
    description: Indicates whether to run kraken
    default: false
  kraken_kmer_length:
    type: integer
    description: Kmer length to use for kraken database
    default: 31
    minimum: 3
  kraken_domains:
    type: array
    description: Domains to download for kraken database
    uniqueItems: true
    items:
      type: string
      enum: ["archaea", "bacteria", "plasmid", "viral", "human"]
    default: ["archaea", "bacteria", "viral"]
  kraken_build_params:
    type: string
    description: Additional build parameters for kraken-build
    default: ""
  centrifuge:
    type: boolean
    description: Indicates whether to run centrifuge classification
    default: false
  mask_low_complexity:
    type: boolean
    description: Whether to mask low-complexity regions for genomes
    default: true
  centrifuge_domains:
    type: array
    description: What domains to use for centrifuge
    uniqueItems: true
    items:
      type: string
      enum: ["bacteria", "viral", "archaea", "fungi", "protozoa", "invertebrate", "plant",
             "vertebrate_mammalian", "vertebrate_other"]
    default: ["viral", "bacteria", "archaea"]
  centrifuge_taxidlist:
    type: string
    description: List of taxonomic ids to download for centrifuge database
    default: ""
  centrifuge_assembly_level:
    type: array
    description: Assembly level(s) to use for centrifuge database
    uniqueItems: true
    items:
      type: string
      enum: ["Complete Genome","Contig","Chromosome","Scaffold"]
    default: ["Complete Genome"]
  centrifuge_summarize_rank:
    type: string
    description: Summarize centrifuge database at what rank
    default: "superkingdom"
  centrifuge_map_filtered:
    type: boolean
    description: Do an additional map of filtered reads back against reference genomes
    default: false
  centrifuge_min_score:
    type: number
    description: Minimum score for considering centrifuge output
    default: 75
  sourmash_fraction:
    type: integer
    description: How many kmer hashes to compute using sourmash (1 in sourmash_fraction)
    default: 100
  sourmash_min_cov:
    type: number
    description: Minimum coverage estimated from sourmash (0.1 = 10% of a genome covered by a sample)
    default: 0.1
  centrifuge_min_read_count:
    type: number
    description: Minimum read count required during pre-filtering with centrifuge
    default: 5000
  centrifuge_max_assignments:
    type: integer
    description: How many maximum number of assignments from centrifuge (set to 1 to implement LCA-classification)
    default: 10
  kaiju:
    type: boolean
    description: Indicates whether to run kaiju
    default: false
type: object
required: [sample_list]