$schema: "http://json-schema.org/draft-04/schema#"
description: Configuration schema
properties:
  ## PATHS ##
  workdir:
    type: string
    default: .
    description: Work directory for workflow
  sample_list:
    type: string
    description: Sample information file
    default: "samples/example_sample_list.tsv"
  taxdb:
    type: string
    description: Directory to store taxonomy information
    default: resources/taxonomy
  results_path:
    type: string
    description: Main results directory
    default: results
  intermediate_path:
    type: string
    description: Intermediate results path
    default: results/intermediate
  temp_path:
    type: string
    description: Temporary path
    default: temp
  scratch_path:
    type: string
    description: Local storage path
    default: "temp"
  resource_path:
    type: string
    description: Path to store resource files (databases etc)
    default: resources
  report_path:
    type: string
    description: Path to store report files
    default: results/report
  pipeline_config_file:
    type: string
    description: File with run information
    default: results/pipeline_config.txt
  ## PREPROCESSING ##
  trimmomatic:
    type: boolean
    description: Indicates whether to run trimmomatic
    default: true
  trimmomatic_home:
    type: string
    description: Path to trimmomatic jar files
    default: ""
  trim_adapters:
    type: boolean
    description: Whether to do adapter trimming with trimmomatic
    default: true
  trimmomatic_pe_adapter:
    type: string
    description: What adapter type to trim from paired end libraries with trimmomatic
    default: TruSeq3-PE-2
    enum: ["NexteraPE-PE", "TruSeq2-PE", "TruSeq3-PE", "TruSeq3-PE-2"]
  trimmomatic_se_adapter:
    type: string
    description: What adapter type to trim from single end libraries with trimmomatic
    default: TruSeq3-SE
    enum: ["TruSeq2-SE", "TruSeq3-SE"]
  pe_adapter_params:
    type: string
    description: Trimmomatic parameters for trimming adapters on paired-end samples
    default: "2:30:15"
  se_adapter_params:
    type: string
    description: Trimmomatic parameters for trimming adapters on single-end samples
    default: "2:30:15"
  pe_pre_adapter_params:
    type: string
    description: Trimmomatic parameters for trimming prior to adapter removal on paired-end samples
    default: ""
  se_pre_adapter_params:
    type: string
    description: Trimmomatic parameters for trimming prior to adapter removal on single-end samples
    default: ""
  pe_post_adapter_params:
    type: string
    description: Trimmomatic parameters for trimming after adapter removal on paired-end samples
    default: "LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:31"
  se_post_adapter_params:
    type: string
    description: Trimmomatic parameters for trimming after adapter removal on single-end samples
    default: "LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:31"
  cutadapt:
    type: boolean
    description: Indicates whether to run cutadapt
    default: false
  adapter_sequence:
    type: string
    description: Adapter sequence to trim with cutadapt
    default: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
  rev_adapter_sequence:
    type: string
    description: Reverse adapter sequence to trim with cutadapt
    default: ""
  cutadapt_error_rate:
    type: number
    default: 0.1
    description: Maximum allowed error rate as value between 0 and 1 (no. of errors divided by length of matching region)
  fastuniq:
    type: boolean
    description: Indicates whether to run fastuniq
    default: false
  phix_filter:
    type: boolean
    description: Indicates whether to filter samples against the phiX genome
    default: false
  sortmerna:
    type: boolean
    description: Indicates whether to identify rRNA sequences in the samples
    default: false
  sortmerna_keep:
    type: string
    description: What to keep from sortmerna filtering (non_rRNA/rRNA)
    default: "non_rRNA"
    enum: ["non_rRNA", "rRNA"]
  sortmerna_remove_filtered:
    type: boolean
    description: Whether to remove filtered reads not specified by sortmerna_keep
    default: false
  sortmerna_dbs:
    type: array
    description: What databases to download for rRNA identification
    uniqueItems: true
    items:
      type: string
      enum: ["rfam-5s-database-id98.fasta","rfam-5.8s-database-id98.fasta","silva-arc-16s-id95.fasta","silva-arc-23s-id98.fasta","silva-bac-16s-id90.fasta","silva-bac-23s-id98.fasta","silva-euk-18s-id95.fasta","silva-euk-28s-id98.fasta"]
    default: ["rfam-5s-database-id98.fasta","rfam-5.8s-database-id98.fasta","silva-arc-16s-id95.fasta","silva-arc-23s-id98.fasta","silva-bac-16s-id90.fasta","silva-bac-23s-id98.fasta","silva-euk-18s-id95.fasta","silva-euk-28s-id98.fasta"]
  sortmerna_paired_strategy:
    type: string
    description: Whether to put both paired reads into rRNA bin (paired_in) or both reads in other bin (paired_out)
    default: "paired_in"
    enum: ["paired_in", "paired_out"]
  sortmerna_params:
    type: string
    description: "Additional parameters for sortmerna"
    default: "--num_alignments 1"
  ## Postprocessing ##
  markduplicates:
    type: boolean
    description: Indicates whether to run MarkDuplicates for removing duplicates post mapping
    default: true
  picard_jar:
    type: string
    description: Path to picard jar file
    default: ""
  picard_path:
    type: string
    description: Path to picard path
    default: ""
  ## Assembly ##
  assembly:
    type: boolean
    description: Indicates whether to run assembly
    default: true
  assembly_threads:
    type: integer
    description: How many threads to use for assembly
    default: 20
    minimum: 1
  megahit_keep_intermediate:
    type: boolean
    description: Whether to keep intermediate contigs from Megahit
    default: false
  megahit_additional_settings:
    type: string
    description: Additional settings for Megahit
    default: "--min-contig-len 300 --prune-level 3"
  metaspades:
    type: boolean
    description: Whether to use Metaspades instead of Megahit for assembly
    default: False
  metaspades_keep_intermediate:
    type: boolean
    description: Whether to keep intermediate contigs from Metaspades
    default: False
  metaspades_keep_corrected:
    type: boolean
    description: Whether to keep corrected reads produced during Metaspades assembly
    default: False
  metaspades_additional_settings:
    type: string
    description: Additional settings for Metaspades
    default: "-k 21,31,41,51,61,71,81,91,101,111,121"
  ## Annotation ##
  tRNAscan:
    type: boolean
    description: Indicates whether to run tRNAscan-SE
    default: true
  infernal:
    type: boolean
    description: Indicates whether to run infernal for rRNA identification
    default: true
  infernal_threads:
    type: integer
    description: How many threads to use for infernal
    default: 8
    minimum: 1
  infernal_dbpath:
    type: string
    description: Where to store infernal database
    default: resources/infernal
  eggnog:
    type: boolean
    description: Indicates whether to run eggnog-mapper
    default: false
  pfam:
    type: boolean
    description: Indicates whether to run pfam_scan
    default: false
  rgi:
    type: boolean
    description: Indicates whether to run Resistance gene identifier on protein fasta file
    default: false
  rgi_params:
    type: string
    description: Parameters for rgi main, outside of the input/output settings
    default: "-a diamond --local --clean --input_type protein"
  taxonomic_annotation:
    type: boolean
    description: Indicates whether to run taxonomic annotation
    default: false
  taxonomy_min_len:
    type: integer
    description: Minimum length of contigs to use for taxonomic annotation
    default: 500
  tango_params:
    type: string
    description: Parameters to use for tango taxonomy assigner
    default: "--evalue 0.001 --top 5"
  taxonomy_ranks:
    type: array
    description: Taxonomic ranks to assign to contigs
    uniqueItems: true
    items:
      type: string
      enum: ["superkingdom","kingdom","phylum","class","order","family","genus","species"]
    default: ["superkingdom","phylum","class","order","family","genus","species"]
  taxdb:
    type: string
    description: Protein database to use for taxonomic annotation
    default: "uniref100"
  diamond_threads:
    type: integer
    description: How many threads to use for diamond
    default: 20
    minimum: 1
  ## Binning ##
  metabat:
    type: boolean
    description: Indicates whether to run Metabat2 to bin contigs
    default: false
  maxbin:
    type: boolean
    description: Indicates whether to run MaxBin2 to bin contigs
    default: false
  maxbin_markerset:
    type: integer
    description: Which marker set to use for Maxbin2 (107=bacteria, 40=bacteria+archaea)
    default: 40
    enum: [40, 107]
  concoct:
    type: boolean
    description: Indicates whether to run Concoct to bin contigs
    default: false
  min_contig_length:
    type: array
    description: Minimum contig lengths for binning
    items:
      type: integer
      minimum: 500
    default: [2000]
  metabat_threads:
    type: integer
    description: Number of threads to use for Metabat2
    default: 20
    minimum: 1
  maxbin_threads:
    type: integer
    description: Number of threads to use for MaxBin2
    default: 10
    minimum: 1
  concoct_threads:
    type: integer
    description: Number of threads to use for Concoct
    default: 20
    minimum: 1
  checkm:
    type: boolean
    description: Indicates whether to check bin quality using checkm
    default: false
  ## Mapping ##
  bowtie2_threads:
    type: integer
    description: How many threads to use for bowtie2
    default: 10
    minimum: 1
  bowtie2_params:
    type: string
    description: Parameters to pass to the bowtie2 aligner
    default: "--very-sensitive"
  ## Classification ##
  kraken:
    type: boolean
    description: Indicates whether to run kraken
    default: false
  kraken_prebuilt:
    type: string
    description: Pre-built kraken index
    default: "minikraken2_v2_8GB"
    enum: ['minikraken2_v1_8GB','minikraken2_v2_8GB','16S_Greengenes','16S_RDP','16S_Silva']
  kraken_custom:
    type: string
    description: Path to directory containing a custom built kraken2 index (must contain 'hash.k2d', 'opts.k2d', 'taxo.k2d')
    default: ""
  kraken_reduce_memory:
    type: boolean
    description: Run kraken2 in '--memory-mapping' mode which avoids loading database into RAM and uses less memory
    default: False
  centrifuge:
    type: boolean
    description: Indicates whether to run centrifuge classification
    default: false
  centrifuge_prebuilt:
    type: string
    description: Pre-built centrifuge index
    default: "p+h+v"
    enum: ["p+h+v", "nt_2018_2_12", "nt_2018_3_3", "p_compressed+h+v", "p_compressed_2018_4_15"]
  centrifuge_custom:
    type: string
    description: Path to custom built centrifuge index (excluding *.cf suffix)
    default: ""
  centrifuge_summarize_rank:
    type: string
    default: "superkingdom"
    enum: ["superkingdom", "kingdom", "phylum", "class", "order", "family", "genus", "species"]
  centrifuge_min_score:
    type: number
    description: Minimum score for considering centrifuge output
    default: 75
  centrifuge_min_read_count:
    type: number
    description: Minimum read count required during pre-filtering with centrifuge
    default: 5000
  centrifuge_max_assignments:
    type: integer
    description: How many maximum number of assignments from centrifuge (set to 1 to implement LCA-classification)
    default: 1
  metaphlan:
    type: boolean
    description: Indicates whether to run metaphlan2 profiler
    default: false
  ## Examples
  example_dataset_size:
    type: integer
    description: Number of reads to subsample into separate example files
    default: 100000
type: object
required: [sample_list]