name: nbis-meta

channels:
  - etetoolkit
  - conda-forge
  - biocore
  - bioconda

dependencies:
  - python>=3.5
  - snakemake>=4.4.0
  - seqtk
  - pandas
  - fastqc
  - bowtie2
  - samtools
  - multiqc
  - cutadapt
  - megahit
  - spades
  - tango
  - tqdm=4.29.1 # Some bug in later version of tqdm causes ZeroDivisionError
  - trimmomatic
  - diamond
  - prodigal
  - hmmer
  - seaborn
  - picard
  - biopython
  - subread
  - sortmerna
  - centrifuge
  - ete3
  - conda
  - sourmash
  - bedtools
  - scikit-bio
  - scikit-learn
  - krona
  - fastuniq
  - gffutils
  - infernal
  - blast
  - kraken2
