name: Docker Image CI

on:
  push:
    branches:
      - develop

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nbis-meta:$(date +%s)
    - name: Run the Docker image
      run: docker run --rm nbis-meta:$(date +%s) --config kraken=True sortmerna=True concoct=True maxbin=True metabat=True -np
