name: CI

on:
  push:
    branches:
      - develop

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
    - name: Install the conda environment
      run: conda env update -n base -f environment.yml
    - name: Dry run
      run: snakemake --use-conda -j 4 --config fastuniq=True kraken=True eggnog=True taxonomic_annotation=True rgi=True pfam=True metabat=True maxbin=True concoct=True checkm=True centrifuge=True -np
    - name: Preprocess
      run: snakemake --use-conda -j 4 -p preprocess && rm -r results
    - name: Cutadapt
      run: snakemake --use-conda -j 4 --config trimmomatic=False cutadapt=True -p preprocess && rm -r results
    - name: Sortmerna
      run: snakemake --use-conda -j 4 --config sortmerna=True -p preprocess && rm -r results
    - name: Metaspades
      run: snakemake --use-conda --config metaspades=True -j 4 -p assembly && rm -r results
    - name: Megahit
      run: snakemake --use-conda --config megahit=True -j 4 -p assembly
    - name: Binning
      run: snakemake --use-conda --config metabat=True concoct=True maxbin=True -j 4 -p binning
