# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:
    branches: 
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - uses: snakemake/snakemake-github-action@v1.6.1
      with:
        directory: .test
        snakefile: Snakefile
        args: "--cores 1 --use-conda -n"
