name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
    - name: Install the conda environment
      run: conda env update -n base -f environment.yml
    - name: Dry run
      run: snakemake --use-conda -j 4 --configfile .test/config/dry-run.yaml -n
    - name: Cutadapt
      run: |
        snakemake --use-conda -j 4 --configfile .test/config/cutadapt.yaml -p --notemp qc
    - name: Upload cutadapt report
      uses: actions/upload-artifact@v1
      with:
        name: ${{ runner.os }}-cutadapt.html
        path: results/report/samples_report.html
    - name: Preprocess
      run: |
        rm -rf results
        snakemake --use-conda -j 4 --configfile .test/config/preprocess.yaml -p qc
    - name: Upload samples report
      uses: actions/upload-artifact@v1
      with:
        name: ${{ runner.os }}-samples_report.html
        path: results/report/samples_report.html
    - name: Kraken
      run: |
        snakemake --use-conda -j 4 --configfile .test/config/kraken.yaml -p results/kraken/sample1_1_pe.kreport results/kraken/sample4_1_se.kreport
    - name: Metaspades
      run: |
        snakemake --use-conda -j 4 --configfile .test/config/metaspades.yaml -p assemble
        rm -r results/assembly results/report examples/data/sample*
    - name: Prepare taxonomy
      run: bash .test/scripts/prep_taxonomy.sh
    - name: Taxonomy
      run: |
        snakemake --use-conda -j 4 --configfile .test/config/taxonomy.yaml -p taxonomy
        rm -r results examples/data/sample*
    - name: Megahit_Metabat
      run: snakemake --use-conda -j 4 --configfile .test/config/metabat.yaml -p bin

  test_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
    - name: Install the conda environment
      run: conda env update -n base -f environment.yml
    - name: Kraken
      run: |
        snakemake --use-conda -j 4 --configfile .test/config/kraken.yaml --notemp -p classify
        rm -r examples/data/sample* results
    - name: Binning
      run: snakemake --use-conda -j 4 --configfile .test/config/binning.yaml -p bin
