name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
    - name: Install the conda environment
      run: conda env update -n base -f environment.yml
    - name: Dry run
      run: snakemake --use-conda -j 4 --configfile .test/config/dry-run.yaml -n
    - name: Cutadapt
      run: snakemake --use-conda -j 4 --configfile .test/config/cutadapt.yaml -p qc && rm -r results
    - name: Sortmerna
      run: snakemake --use-conda -j 4 --configfile .test/config/sortmerna.yaml -p qc
    - name: Metaspades
      run: snakemake --use-conda -j 4 --configfile .test/config/metaspades.yaml -p assemble && rm -r results/assembly && rm -r results/report
    - name: Megahit
      run: snakemake --use-conda -j 4 --configfile .test/config/megahit.yaml -p assemble
    - name: Kraken
      run: snakemake --use-conda -j 4 --configfile .test/config/kraken.yaml -p results/kraken/sample1_1_pe.kreport results/kraken/sample3_1_se.kreport && rm -r examples/data results/
    - name: Preprocess
      run: snakemake --use-conda -j 4 --configfile .test/config/preprocess.yaml -p qc
    - name: Metabat
      run: snakemake --use-conda -j 4 --configfile .test/config/metabat.yaml -p bin
    - name: Prepare taxonomy
      run: bash .test/scripts/prep_taxonomy.sh
    - name: Taxonomy
      run: snakemake --use-conda -j 4 --configfile .test/config/taxonomy.yaml -p taxonomy

  test_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Kraken
      run: snakemake --use-conda -j 4 --configfile .test/config/kraken.yaml -p classify
    - name: Binning
      run: snakemake --use-conda -j 4 --configfile .test/config/binning.yaml -p bin
